name: leapvo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - matplotlib
  - pandas=2.2.2
  - scipy=1.13.1
  - pytorch=1.13.0
  - torchvision=0.14.0
  - cudatoolkit=11.6
  - ninja
  - ca-certificates
  - certifi
  - libffi
  - openssl
  - setuptools
  - wheel
  - pip:
      - antlr4-python3-runtime==4.9.3
      - argcomplete==3.3.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==4.4.2
      - einops==0.8.0
      - evo==1.28.0
      - filelock==3.14.0
      - fonttools==4.53.0
      - fsspec==2024.6.0
      - huggingface-hub==0.23.3
      - hydra-core==1.3.2
      - imageio==2.19.3
      - imageio-ffmpeg==0.4.9
      - kiwisolver==1.4.5
      - lz4==4.3.3
      - moviepy==1.0.3
      - natsort==8.4.0
      - numexpr==2.10.0
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - packaging==24.0
      - proglog==0.1.10
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - rosbags==0.10.2
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.3
      - seaborn==0.13.2
      - six==1.16.0
      - timm==1.0.3
      - torch-scatter==2.1.2
      - tqdm==4.66.4
      - tzdata==2024.1
      - zstandard==0.22.0
